services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./.infrastructure/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./app/public:/var/www/html/public
  app:
    build:
      dockerfile: ./.infrastructure/php/Dockerfile
      target: "${BUILD_TARGET:-app}"
    volumes:
      - ./app:/var/www/html
      - ./.infrastructure/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    environment:
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      - host.docker.internal:host-gateway